KNOWN_BRANDS = {
    'AC', 'ACURA', 'ALFA_ROMEO', 'ALPINE', 'AMG', 'ASTON_MARTIN', 'AUDI', 'AURUS',
    'ABARTH', 'BENTLEY', 'BMW', 'BRISTOL', 'BUFORI', 'BUGATTI', 'BUICK', 'CADILLAC',
    'CATERHAM', 'CHEVROLET', 'CHRYSLER', 'CITROEN', 'CUPRA', 'DACIA', 'DAEWOO',
    'DAIHATSU', 'DATSUN', 'DELOREAN', 'DINO', 'DODGE', 'DS', 'DS_AUTOMOBILES',
    'FERRARI', 'FIAT', 'FISKER', 'FOCUS', 'FORD', 'GENESIS', 'GMC', 'HOLDEN',
    'HONDA', 'HYUNDAI', 'INFINITI', 'ISUZU', 'JAGUAR', 'JEEP', 'KIA', 'KOENIGSEGG',
    'KTM', 'LADA', 'LAMBORGHINI', 'LANCIA', 'LANCER', 'LAND_ROVER', 'LEXUS',
    'LIGHTYEAR', 'LINCOLN', 'MASERATI', 'MAYBACH', 'MAZDA', 'MERCEDESBENZ',
    'MERCEDES_BENZ', 'MERCEDESAMG', 'MERCEDESBEN', 'MEREDESBENZ', 'MG', 'MINI',
    'MITSUBISHI', 'NISSAN', 'OPEL', 'PEUGEOT', 'PININFARINA', 'PORSCHE',
    'RANGE_ROVER', 'RENAULT', 'ROLLSROYCE', 'SAAB', 'SEAT', 'SKODA', 'SMART',
    'SSANGYONG', 'SUBARU', 'SUZUKI', 'TESLA', 'TOYOTA', 'VAUXHALL', 'VOLKSWAGEN',
    'VW', 'VOLVO', 'WIESMANN'
    }

NORMALIZED_BRANDS = {
        'MERCEDESBENZ': 'MERCEDES',
        'MERCEDES_BENZ': 'MERCEDES',
        'MERCEDESAMG': 'MERCEDES',
        'MERCEDESBEN': 'MERCEDES',
        'MEREDESBENZ': 'MERCEDES',
        'AMG': 'MERCEDES',
        'DS_AUTOMOBILES': 'DS',
        'VW': 'VOLKSWAGEN'
        }
