KNOWN_BRANDS = {
    'ACURA', 'ALFA_ROMEO', 'ALPINE', 'ASTON_MARTIN', 'AUDI', 'BENTLEY', 'BMW',
    'BUGATTI', 'BUICK', 'CADILLAC', 'CATERHAM', 'CHEVROLET', 'CHRYSLER',
    'CITROEN', 'CUPRA', 'DACIA', 'DAEWOO', 'DAIHATSU', 'DATSUN', 'DODGE',
    'DS', 'DS_AUTOMOBILES', 'DELOREAN', 'FERRARI', 'FIAT', 'FISKER', 'FORD',
    'GENESIS', 'GMC', 'HOLDEN', 'HONDA', 'HYUNDAI', 'INFINITI', 'ISUZU',
    'JAGUAR', 'JEEP', 'KIA', 'KOENIGSEGG', 'KTM', 'LADA', 'LAMBORGHINI',
    'LANCIA', 'LAND_ROVER', 'LEXUS', 'LINCOLN', 'MASERATI', 'MAYBACH',
    'MAZDA', 'MERCEDESBENZ', 'MERCEDES_BENZ', 'MERCEDESAMG', 'MG', 'MINI',
    'MITSUBISHI', 'NISSAN', 'OPEL', 'PEUGEOT', 'PININFARINA', 'PORSCHE',
    'RANGE_ROVER', 'RENAULT', 'ROLLSROYCE', 'SAAB', 'SEAT', 'SKODA', 'SMART',
    'SSANGYONG', 'SUBARU', 'SUZUKI', 'TESLA', 'TOYOTA', 'VAUXHALL', 'VOLKSWAGEN',
    'VOLVO', 'WIESMANN'
    }

NORMALIZED_BRANDS = {
        'MERCEDESBENZ': 'MERCEDES',
        'MERCEDES_BENZ': 'MERCEDES',
        'MERCEDESAMG': 'MERCEDES',
        'DS_AUTOMOBILES': 'DS',
        'VW': 'VOLKSWAGEN'
        }
